server {
    listen 8080;
    root /usr/share/nginx/html;

    location /bundles/ {
        autoindex on;
        add_header ETag $upstream_http_etag;
        types {
            application/gzip tar.gz;
        }
    }
}
