capi:
  version: 1.0.0
  instanceName: default
  strictToInstanceName: false
  publicEndpoint: http://localhost:8380/api/
  runningMode: full
  adminPort: 8381
  reverseProxyHost:
  rest:
    enabled: true
    port: 8380
    listeningAddress: 0.0.0.0
    contextPath: /api
    connectionRequestTimeout: 5000
    requestTimeout: 5000
    responseTimeout: 120000
  websocket:
    enabled: false
    port: 8382
    listeningAddress: 0.0.0.0
    contextPath: /api/*
  grpc:
    enabled: false
    port: 8384
  ssl:
    enabled: false
    keyStoreType: PKCS12
    path:
    password:
  trustStore:
    enabled: false
    path:
    encoded:
    password:
  consulCatalogDiscoverInterval: 10000
  consulHosts:
    - endpoint: http://consul:8500
      token:
  consulStore:
    enabled: false
    endpoint: http://consul:8500
    token:
  oauth2:
    enabled: false
    cookieName:
    keys:
      - http://keycloak:8080/realms/capi/protocol/openid-connect/certs
  opa:
    enabled: false
    endpoint: http://opa:8181
  traces:
    enabled: true
    serviceName: capi
    endpoint: http://otel-collector:4318
    extraMetadataPrefix:
  corsEnabled: false
  allowedHeaders:
    - Origin
    - Accept
    - X-Requested-With
    - Content-Type
    - Access-Control-Request-Method
    - Authorization
  loggingTraces:
    enabled: false
    tenant: capi
    appName: capi
    appEnvironment: dev
    destination: otel-collector:5444
    filePath:
  accessLogs:
    enabled: false
    tenant: capi
    service: capi
    destination: otel-collector:5444
    filePath:
  throttle:
    enabled: false