package io.surisoft.capi.metrics;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.surisoft.capi.schema.Service;
import org.apache.camel.util.json.JsonArray;
import org.apache.camel.util.json.JsonObject;
import org.cache2k.Cache;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class OpenAPIDefinition {

    private final Cache<String, Service> serviceCache;
    private final String capiPublicEndpoint;

    public OpenAPIDefinition(Cache<String, Service> serviceCache, String capiPublicEndpoint) {
        this.serviceCache = serviceCache;
        this.capiPublicEndpoint = capiPublicEndpoint;
    }

    public JsonObject getCacheOpenApiDefinition(Service service, ObjectMapper objectMapper, String serviceName) {
        try {
            if(service.getServiceMeta() != null && service.getServiceMeta().getOpenApiEndpoint() != null) {
                HttpClient client = HttpClient.newBuilder().build();
                HttpRequest request = HttpRequest.newBuilder().uri(URI.create(service.getServiceMeta().getOpenApiEndpoint())).build();
                HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
                JsonObject serverObject = new JsonObject();
                serverObject.put("url", capiPublicEndpoint + serviceName.replaceAll(":", "/"));
                JsonObject responseObject = objectMapper.readValue(response.body(), JsonObject.class);
                responseObject.remove("servers");

                JsonArray serversArray = new JsonArray();
                serversArray.add(serverObject);

                JsonObject infoObject = new JsonObject();
                infoObject.put("title", service.getId());
                infoObject.put("description", "Open API definition generated by CAPI");
                responseObject.put("info", infoObject);
                responseObject.put("servers", serversArray);
                return responseObject;
            }
            return null;
        } catch (NullPointerException | IOException | InterruptedException e) {
            return null;
        }
    }

    public Service getCachedService(String serviceName) {
        if(serviceCache.containsKey(serviceName)) {
            return serviceCache.get(serviceName);
        }
        return null;
    }
}