package io.surisoft.capi.metrics;

import io.surisoft.capi.schema.Service;
import io.swagger.v3.core.util.Json;
import io.swagger.v3.oas.models.OpenAPI;
import org.cache2k.Cache;

import java.util.*;

public class OpenAPIDefinition {

    private final Cache<String, Service> serviceCache;
    private final String capiPublicEndpoint;

    public OpenAPIDefinition(Cache<String, Service> serviceCache, String capiPublicEndpoint) {
        this.serviceCache = serviceCache;
        this.capiPublicEndpoint = capiPublicEndpoint;
    }

    @SuppressWarnings("unchecked")
    public Map<String, Object> getCacheOpenApiDefinition(Service service, String serviceName) {
        OpenAPI openAPI = service != null ? service.getOpenAPI() : null;
        if (openAPI == null) {
            return null;
        }
        try {
            Map<String, Object> responseObject = new LinkedHashMap<>(
                    Json.mapper().convertValue(openAPI, Map.class));

            Map<String, Object> serverObject = new LinkedHashMap<>();
            serverObject.put("url", capiPublicEndpoint + serviceName.replaceAll(":", "/"));
            List<Map<String, Object>> serversArray = new ArrayList<>();
            serversArray.add(serverObject);

            Map<String, Object> infoObject = new LinkedHashMap<>();
            infoObject.put("title", service.getId());
            infoObject.put("description", "Open API definition generated by CAPI");

            responseObject.remove("servers");
            responseObject.put("info", infoObject);
            responseObject.put("servers", serversArray);
            return responseObject;
        } catch (IllegalArgumentException e) {
            return null;
        }
    }

    public Service getCachedService(String serviceName) {
        if(serviceCache.containsKey(serviceName)) {
            return serviceCache.get(serviceName);
        }
        return null;
    }
}
