{{- if or .Values.capi.ssl.enabled .Values.capi.trustStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capi-core.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-core.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.capi.ssl.enabled }}
  keystore.p12: {{ .Values.capi.ssl.keystoreBase64 }}
  ssl-password: {{ .Values.capi.ssl.password | b64enc }}
  {{- end }}
  {{- if .Values.capi.trustStore.enabled }}
  truststore.jks: {{ .Values.capi.trustStore.datastoreBase64 }}
  truststore-password: {{ .Values.capi.trustStore.password | b64enc }}
  {{- end }}
{{- end }}
