apiVersion: v1
kind: Service
metadata:
  name: {{ include "capi-core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.restPort }}
      targetPort: rest
      protocol: TCP
      name: rest
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    {{- if .Values.capi.websocket.enabled }}
    - port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    {{- end }}
  selector:
    {{- include "capi-core.selectorLabels" . | nindent 4 }}
