package io.surisoft.capi.metrics;

import io.surisoft.capi.schema.Service;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.Paths;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.servers.Server;
import org.cache2k.Cache;
import org.cache2k.Cache2kBuilder;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
class OpenAPIDefinitionTest {

    private Cache<String, Service> serviceCache;
    private OpenAPIDefinition openAPIDefinition;

    @BeforeEach
    void setUp() {
        serviceCache = Cache2kBuilder.of(String.class, Service.class)
                .name("openApiDefTestCache-" + System.nanoTime())
                .eternal(true)
                .build();
        openAPIDefinition = new OpenAPIDefinition(serviceCache, "http://localhost:8080/");
    }

    @AfterEach
    void tearDown() {
        if (serviceCache != null) {
            serviceCache.close();
        }
    }

    @Test
    void getCacheOpenApiDefinition_nullService_returnsNull() {
        assertNull(openAPIDefinition.getCacheOpenApiDefinition(null, "test:service"));
    }

    @Test
    void getCacheOpenApiDefinition_serviceWithoutCachedOpenAPI_returnsNull() {
        Service service = new Service();
        service.setId("test-service");
        // service.openAPI never set

        assertNull(openAPIDefinition.getCacheOpenApiDefinition(service, "test:service"));
    }

    @Test
    void getCacheOpenApiDefinition_cachedOpenAPI_returnsEnrichedDefinition() {
        OpenAPI openAPI = new OpenAPI()
                .info(new Info().title("Original").version("1.0"))
                .servers(List.of(new Server().url("http://old-backend")))
                .paths(new Paths().addPathItem("/hello", new PathItem()));

        Service service = new Service();
        service.setId("my-svc");
        service.setOpenAPI(openAPI);

        Map<String, Object> result = openAPIDefinition.getCacheOpenApiDefinition(service, "my-svc:v1");
        assertNotNull(result, "Expected non-null result when service has cached OpenAPI");
        assertNotNull(result.get("paths"));

        @SuppressWarnings("unchecked")
        Map<String, Object> info = (Map<String, Object>) result.get("info");
        assertEquals("my-svc", info.get("title"));
        assertEquals("Open API definition generated by CAPI", info.get("description"));

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> servers = (List<Map<String, Object>>) result.get("servers");
        assertEquals(1, servers.size());
        assertEquals("http://localhost:8080/my-svc/v1", servers.get(0).get("url"));
    }

    @Test
    void getCachedService_exists_returnsService() {
        Service service = new Service();
        service.setId("my-service");

        serviceCache.put("my-service", service);

        Service result = openAPIDefinition.getCachedService("my-service");
        assertNotNull(result);
        assertEquals("my-service", result.getId());
    }

    @Test
    void getCachedService_doesNotExist_returnsNull() {
        assertNull(openAPIDefinition.getCachedService("nonexistent-service"));
    }

    @Test
    void getCachedService_multipleEntries_returnsCorrectOne() {
        Service service1 = new Service();
        service1.setId("service-1");
        Service service2 = new Service();
        service2.setId("service-2");

        serviceCache.put("service-1", service1);
        serviceCache.put("service-2", service2);

        Service result = openAPIDefinition.getCachedService("service-2");
        assertNotNull(result);
        assertEquals("service-2", result.getId());
    }
}